home_path: /root
daft_repo_url: https://github.com/01org/DAFT.git
daft_repo_path: "{{ home_path }}/DAFT"
daft_testing_harness_path: "{{ daft_repo_path }}/testing_harness"
daft_testing_harness_extras_path: "{{ daft_repo_path }}/testing_harness_image_extras"
aft_init_scripts_path: "{{ daft_testing_harness_extras_path }}/initialize_testing_harness"
aft_init_scripts_dest_path: /usr/bin
systemd_system_path: /etc/systemd/system
multi_user_target_wants_path: /etc/systemd/system/multi-user.target.wants
aft_external_interface: eth0
aft_internal_interface: usb0
dut_dest_port: 2233
dut_ip_address: 192.168.7.2
dut_port: 22
iptables_conf_file_path: /etc/iptables.rules
sysctl_conf_file_path: /etc/sysctl.conf
network_if_conf_file_path: /etc/network/interfaces
dnsmasq_conf_file_path: /etc/dnsmasq.conf
fstab_conf_file_path: /etc/fstab
home_ssh_conf_file_path: "{{ home_path }}/.ssh/config"
ssh_identity_file_path: "{{ home_path }}/.ssh/id_rsa_testing_harness"
dhcp_lease_time: 10m
ntp_conf_file_path: /etc/ntp.conf
ntpdate_conf_file_path: /etc/default/ntpdate
