- name: remove not required boot scripts
  file: path=/opt/scripts/boot/{{ item }} state=absent
  with_items:
  - am335x_evm.sh
  - autoconfigure_usb0.sh
  - capemgr.sh

- name: disable not required services
  service: name={{ item }} enabled=no
  with_items:
  - connman

- name: install required packages
  apt: pkg={{ item }} state=latest
  with_items:
  - nfs-common
  - dnsmasq
  - python3-setuptools
  - python3-pip
  - expect
  - ntp
  - ntpdate
  - psmisc

- name: install required Python libraries 
  pip: executable=pip3 name={{ item }} state=latest
  with_items:
  - pyserial
  - netifaces
  - unittest-xml-reporting

- name: configure https proxy for git
  git_config: scope=global name=https.proxy value={{ https_proxy }}

- name: configure http proxy for git
  git_config: scope=global name=http.proxy value={{ http_proxy }}

- name: clone DAFT repository
  git: repo=https://github.com/01org/DAFT dest=/root/DAFT

- name: install AFT
  shell: "cd /root/DAFT/testing_harness; python3 ./setup.py install"
