- name: remove not required boot scripts
  file: path=/opt/scripts/boot/{{ item }} state=absent
  with_items:
  - am335x_evm.sh
  - autoconfigure_usb0.sh
  - capemgr.sh

- name: disable not required services
  service: name={{ item }} enabled=no
  with_items:
  - connman

- name: install required packages
  apt: pkg={{ item }} state=latest
  with_items:
  - nfs-common
  - dnsmasq
  - python3-setuptools
  - python3-pip
  - expect
  - ntp
  - ntpdate
  - psmisc

- name: install required Python libraries 
  pip: executable=pip3 name={{ item }} state=latest
  with_items:
  - pyserial
  - netifaces
  - unittest-xml-reporting

- name: configure https proxy for git
  git_config: scope=global name=https.proxy value={{ https_proxy }}
  tags: aft_install

- name: configure http proxy for git
  git_config: scope=global name=http.proxy value={{ http_proxy }}
  tags: aft_install

- name: clone DAFT repository
  git: repo={{ daft_repo_url }} dest={{ daft_repo_path }}
  tags: aft_install

- name: install AFT
  shell: "cd {{ daft_testing_harness_path }}; python3 ./setup.py install"
  tags: aft_install

- name: copy AFT initialization scripts
  copy:
    src: "{{ aft_init_scripts_path }}/{{ item }}"
    dest: "{{ aft_init_scripts_dest_path }}"
    remote_src: True
  with_items:
  - stop_libcomposite
  - start_libcomposite
  - initialize_testing_harness
  tags: aft_init

- name: copy AFT initialization services to systemd path
  copy:
    src: "{{ aft_init_scripts_path }}/{{ item }}"
    dest: "{{ systemd_system_path }}"
    remote_src: True
  with_items:
  - initialize_testing_harness.service
  - libcomposite.service
  tags: aft_init

- name: enable AFT initialization services
  file:
    src: "{{ systemd_system_path }}/{{ item }}"
    dest: "{{ multi_user_target_wants_path }}/{{ item }}"
    state: link
  with_items:
  - initialize_testing_harness.service
  - libcomposite.service
  tags: aft_init

- name: copy AFT kbsequences directory
  command: cp -ruv {{ daft_testing_harness_extras_path }}/kbsequences {{ home_path }}
  register: kbsequences_cp_output
  changed_when: kbsequences_cp_output.stdout != ""
  tags: aft_init

- name: create required folders for test harness
  file: path="{{ item }}" state=directory
  with_items:
  - "{{ home_path }}/support_image"
  - "{{ home_path }}/workspace"
  - "{{ home_path }}/.ssh"
  - /ramdisk
  - /config
  tags: aft_init

- name: copy /var directory
  command: cp -ruv /var /_var
  register: var_cp_output
  changed_when: var_cp_output.stdout != ""
  tags: aft_init
